### ISSUE TITLE
Updates to metalink

### ISSUE THREAD

**Issue by lnguyen** [dpb587/metalink#5]
Hey Danny!  We(vmware) are looking to update metalink to support aws assume roles, are you okay with us making PR and cutting a new release? We probably need to do same for concourse resources we use

**Comment by dpb587** [comment]
Hi - yeah, feel free to PR and I can merge and build/push, probably by adding GitHub Actions. Same for concourse resource repositories. I don't personally use these workflows anymore, so won't be able to offer much detailed feedback. If you have longer-term maintenance or PRs in mind, I'd suggest adding you/team as a collaborator or have you switch to a fork and archive this instead.

For what it's worth, last I knew on the Concourse side, relying on STS directly from worker containers can become an anti-pattern and complex in some environments, but leave those considerations up to you all.

**Comment by lnguyen** [comment]
Thanks!!
